-- iFood Catalog publish identity. The item/product ids are UUID v4 generated by MenuBank
-- on the first publish and reused on every republish, so PUT /items stays idempotent and
-- never duplicates an item on the iFood side. All nullable: a product is simply
-- "not published yet" until the first successful publish.
alter table products
    add column ifood_item_id varchar(36);
alter table products
    add column ifood_product_id varchar(36);
alter table products
    add column ifood_published_at timestamp;
